name: CD - Generar WAR

on:
  workflow_run:
    workflows: ["CI - Ejecutar Tests"]
    types:
      - completed

jobs:
  deploy:
    # Solo se ejecuta si el workflow de CI ha pasado correctamente
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      # Descarga el código del repositorio
      - name: Checkout código
        uses: actions/checkout@v3

      # Configura Java 21
      - name: Configurar Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Empaqueta la aplicación en un fichero WAR
      - name: Generar WAR con Maven
        run: ./mvnw clean package -DskipTests

      # Sube el WAR como artefacto descargable
      - name: Subir WAR como artefacto
        uses: actions/upload-artifact@v3
        with:
          name: ExamenGallegoVictorDI
          path: target/*.war
